### ISSUE TITLE
Error running in Python 3.5

### ISSUE THREAD

**Issue by dburkhardt** [jxz12/s_gd2#22]
Hi, I'm getting this error when I try to import s_gd2 on Travis

```
ERROR: test_benchmark.transplant_class.<locals>.C (test_benchmarker_EES)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/s_gd2/swig/layout.py", line 18, in swig_import_helper

    fp, pathname, description = imp.find_module('_layout', [dirname(__file__)])

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/imp.py", line 297, in find_module

    raise ImportError(_ERR_MSG.format(name), name=name)

ImportError: No module named '_layout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/KrishnaswamyLab/MELD/test/test_benchmark.py", line 22, in test_benchmarker_EES

    benchmarker.fit_phate(data, verbose=False)

  File "/home/travis/build/KrishnaswamyLab/MELD/meld/benchmark.py", line 131, in fit_phate

    import phate

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/phate/__init__.py", line 3, in <module>

    from .phate import PHATE

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/phate/phate.py", line 19, in <module>

    from . import utils, vne, mds

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/phate/mds.py", line 14, in <module>

    import s_gd2

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/s_gd2/__init__.py", line 1, in <module>

    from .s_gd2 import *

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/s_gd2/s_gd2.py", line 1, in <module>

    from .swig import layout as cpp

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/s_gd2/swig/layout.py", line 28, in <module>

    _layout = swig_import_helper()

  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/s_gd2/swig/layout.py", line 20, in swig_import_helper

    import _layout

ImportError: numpy.core.multiarray failed to import
```

The full output of the travis job can be found here: https://travis-ci.com/github/KrishnaswamyLab/MELD/jobs/384703285

**Comment by jxz12** [comment]
I'll have a look some time this week! @scottgigante may also be able to help as he was the one who kindly set up Travis on the package.

**Comment by scottgigante** [comment]
I suspect it's a versioning issue -- maybe the version of numpy this was built with is different from the version you're running. @dburkhardt can you print the relevant version numbers?

**Comment by dburkhardt** [comment]
```
$ pip install .[test]

Processing /home/travis/build/KrishnaswamyLab/MELD

Requirement already satisfied: numpy>=1.14.0 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (1.15.4)

Requirement already satisfied: scipy>=1.1.0 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (1.4.1)

Requirement already satisfied: graphtools>=1.5.0 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (1.5.2)

Requirement already satisfied: pandas>=0.25 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (0.25.3)

Requirement already satisfied: scprep>=1.0 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (1.0.5.post2)

Requirement already satisfied: pygsp in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (0.5.1)

Requirement already satisfied: sklearn in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (0.0)

Requirement already satisfied: nose in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (1.3.7)

Collecting nose2 (from meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/b9/ad/27561695e863f5df064f1715864afb3ebe723a6e19e875eca85570e0a7cd/nose2-0.9.2-py2.py3-none-any.whl

Collecting coverage (from meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/35/58/e38636e8233b49982efca6a69c9974f2575439f637dc3b0e8ac0e77c550c/coverage-5.3-cp35-cp35m-manylinux1_x86_64.whl

Collecting coveralls (from meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/18/41/818c8fae7c6295fdbaab45e2627fddb460e9a999aa1aea503ca0d9bf59d9/coveralls-2.1.2-py2.py3-none-any.whl

Requirement already satisfied: scikit-learn in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (0.22.2.post1)

Collecting packaging (from meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl

Requirement already satisfied: matplotlib in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (3.0.3)

Collecting parameterized (from meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/ba/6b/73dfed0ab5299070cf98451af50130989901f50de41fe85d605437a0210f/parameterized-0.7.4-py2.py3-none-any.whl

Requirement already satisfied: phate in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from meld==0.3.0a0) (1.0.4)

Requirement already satisfied: future in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from graphtools>=1.5.0->meld==0.3.0a0) (0.18.2)

Requirement already satisfied: Deprecated in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from graphtools>=1.5.0->meld==0.3.0a0) (1.2.10)

Requirement already satisfied: tasklogger>=1.0 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from graphtools>=1.5.0->meld==0.3.0a0) (1.0.0)

Requirement already satisfied: python-dateutil>=2.6.1 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from pandas>=0.25->meld==0.3.0a0) (2.8.1)

Requirement already satisfied: pytz>=2017.2 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from pandas>=0.25->meld==0.3.0a0) (2020.1)

Requirement already satisfied: decorator>=4.3.0 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from scprep>=1.0->meld==0.3.0a0) (4.4.2)

Requirement already satisfied: six>=1.7 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from nose2->meld==0.3.0a0) (1.12.0)

Requirement already satisfied: mock==2.0.0; python_version < "3.6" in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from nose2->meld==0.3.0a0) (2.0.0)

Collecting docopt>=0.6.1 (from coveralls->meld==0.3.0a0)

Collecting requests>=1.0.0 (from coveralls->meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl

Requirement already satisfied: joblib>=0.11 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from scikit-learn->meld==0.3.0a0) (0.14.1)

Requirement already satisfied: pyparsing>=2.0.2 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from packaging->meld==0.3.0a0) (2.4.7)

Requirement already satisfied: kiwisolver>=1.0.1 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from matplotlib->meld==0.3.0a0) (1.1.0)

Requirement already satisfied: cycler>=0.10 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from matplotlib->meld==0.3.0a0) (0.10.0)

Requirement already satisfied: s-gd2>=1.5 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from phate->meld==0.3.0a0) (1.8)

Requirement already satisfied: wrapt<2,>=1.10 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from Deprecated->graphtools>=1.5.0->meld==0.3.0a0) (1.12.1)

Requirement already satisfied: pbr>=0.11 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from mock==2.0.0; python_version < "3.6"->nose2->meld==0.3.0a0) (5.1.1)

Requirement already satisfied: certifi>=2017.4.17 in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from requests>=1.0.0->coveralls->meld==0.3.0a0) (2018.11.29)

Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=1.0.0->coveralls->meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl

Collecting idna<3,>=2.5 (from requests>=1.0.0->coveralls->meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl

Collecting chardet<4,>=3.0.2 (from requests>=1.0.0->coveralls->meld==0.3.0a0)

  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl

Requirement already satisfied: setuptools in /home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages (from kiwisolver>=1.0.1->matplotlib->meld==0.3.0a0) (40.6.3)

Building wheels for collected packages: meld

  Running setup.py bdist_wheel for meld: started

  Running setup.py bdist_wheel for meld: finished with status 'done'

  Stored in directory: /tmp/pip-ephem-wheel-cache-yrcvpk_e/wheels/2e/0a/5c/10aa074f9e701c8e65a34c242a5fe83947fe0326817810911f

Successfully built meld

Installing collected packages: coverage, nose2, docopt, urllib3, idna, chardet, requests, coveralls, packaging, parameterized, meld

  Found existing installation: meld 0.3.0a0

    Uninstalling meld-0.3.0a0:

      Successfully uninstalled meld-0.3.0a0

Successfully installed chardet-3.0.4 coverage-5.3 coveralls-2.1.2 docopt-0.6.2 idna-2.10 meld-0.3.0a0 nose2-0.9.2 packaging-20.4 parameterized-0.7.4 requests-2.24.0 urllib3-1.25.10
```

**Comment by scottgigante** [comment]
You're using numpy 1.15 when `s_gd2`'s `setup.py` requires numpy>=1.16.
